### ISSUE TITLE
Automatic requests splitting

### ISSUE THREAD

**Issue by ffeast** [ffeast/finam-export#4]
Finam has restrictions on the longest data period that can be requested.
This period seems to depend on the timeframe used. 
It's reasonable and prevents users from fetching too much data in one go - i.e. requesting 10-years long tick data would result in enormous data volume.  

Now if the user specifies a time period which is too long an error is produced (`FinamTooLongTimeframeError`)

It would be nice to have an option resulting in automatic splitting of such long periods so that the user doesn't need to guess whether the period he needs is too long for finam servers. 

Of course `--delay` argument of the downloader scripts must be honored or even enforced

**Comment by zaxash** [comment]
Hello ffeast. I am really impressed with your tool. I was experimenting with a script which downloads data from many symbols and timeframes. I might have a solution for the issue, but I do not know what time period is too long for each timeframe.
Also, I believe I was getting errors in my script because I was requesting data from finam too fast. Do you know what the required delay that you mentioned is?

**Comment by ffeast** [comment]
Hi @zaxash 
> I do not know what time period is too long for each timeframe.
Nobody knows )) It can be checked only via experiments

> Also, I believe I was getting errors in my script because I was requesting data from finam too fast. Do you know what the required delay that you mentioned is?
Just try to increase the delay, no recommendations here. I use the default delay (1 second) and it works fine for me

**Comment by ffeast** [comment]
Anyone to send a pull request for this?
